#!/usr/bin/env python

import image_saver_ros.image_saver
import rospy

if __name__ == '__main__':

    # Initiating ros node
    rospy.init_node('image_saver', anonymous=False)

    saver = image_saver_ros.image_saver.ImageSaver()
    try:
        saver.loop()
    except rospy.exceptions.ROSInterruptException:
        pass
